"""initial schema

Revision ID: 2ad818202900
Revises:
Create Date: 2026-08-15 21:29:36.327924
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op


revision: str = "2ad818202900"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Must precede any table using the vector type. Alembic's autogenerate does not
    # know extensions exist, so without this line the migration only ever works on a
    # database where someone already ran it by hand — which is to say, ours, and
    # nobody else's.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corpus",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "model_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    op.create_index("ix_model_cache_stage", "model_cache", ["stage"], unique=False)
    op.create_table(
        "rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ruleset_id", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("predicate", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "kind IN ('numeric_bound','numeric_max','numeric_min','presence_required')",
            name="ck_rule_kind",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ruleset_id", "code", name="uq_rule_ruleset_code"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=True),
        sa.Column("kind_confidence", sa.Float(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "sha256", name="uq_document_corpus_sha256"),
    )
    op.create_index("ix_document_corpus", "document", ["corpus_id"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("parent_run_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('running','awaiting_review','completed','failed','escalated')",
            name="ck_run_status",
        ),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_run_id"], ["run.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_run_corpus", "run", ["corpus_id"], unique=False)
    op.create_table(
        "section",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("corpus_id", sa.UUID(), nullable=False),
        sa.Column("section_key", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.CheckConstraint("kind IN ('register_row','narrative')", name="ck_section_kind"),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpus.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corpus_id", "section_key", name="uq_section_corpus_key"),
    )
    op.create_table(
        "chunk",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunk_document_ordinal"),
    )
    op.create_index("ix_chunk_document", "chunk", ["document_id"], unique=False)
    op.create_table(
        "decision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('approved','rejected','deferred')", name="ck_decision_verdict"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_decision_run", "decision", ["run_id"], unique=False)
    op.create_table(
        "finding",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_kind", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open','approved','rejected')", name="ck_finding_status"),
        sa.ForeignKeyConstraint(["rule_id"], ["rule.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_finding_run", "finding", ["run_id"], unique=False)
    op.create_table(
        "section_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("section_key", sa.String(length=200), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_version_id", sa.UUID(), nullable=True),
        sa.Column("carried_forward", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["prev_version_id"], ["section_version.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "section_key", name="uq_section_version_run_key"),
    )
    op.create_index("ix_section_version_key", "section_version", ["section_key"], unique=False)
    op.create_table(
        "stage_metric",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column(
            "started", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ended", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("cache_hits", sa.Integer(), nullable=False),
        sa.Column("cache_misses", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_stage_metric_run", "stage_metric", ["run_id"], unique=False)
    op.create_table(
        "claim",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("section_version_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('supported','unsupported','conflicted')", name="ck_claim_status"
        ),
        sa.ForeignKeyConstraint(["section_version_id"], ["section_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_claim_section_version", "claim", ["section_version_id"], unique=False)
    op.create_table(
        "fact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=True),
        sa.Column("predicate", sa.String(length=80), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("value_raw", sa.Text(), nullable=False),
        sa.Column("value_norm", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("extractor_version", sa.String(length=40), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunk.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["superseded_by"], ["fact.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fact_document", "fact", ["document_id"], unique=False)
    op.create_index("ix_fact_predicate_subject", "fact", ["predicate", "subject"], unique=False)
    op.create_table(
        "claim_citation",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claim.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "fact_id"),
    )
    op.create_table(
        "conflict",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("a_fact_id", sa.UUID(), nullable=False),
        sa.Column("b_fact_id", sa.UUID(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("adjudicated", sa.Boolean(), nullable=False),
        sa.Column("detected_in_run", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("severity IN ('low','medium','high')", name="ck_conflict_severity"),
        sa.CheckConstraint("status IN ('open','accepted','dismissed')", name="ck_conflict_status"),
        sa.ForeignKeyConstraint(["a_fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["b_fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["detected_in_run"], ["run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("a_fact_id", "b_fact_id", "kind", name="uq_conflict_pair_kind"),
    )
    op.create_table(
        "finding_evidence",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["finding_id"], ["finding.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id", "fact_id"),
    )
    op.create_table(
        "section_dependency",
        sa.Column("section_key", sa.String(length=200), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["fact.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("section_key", "fact_id"),
    )
    op.create_index("ix_section_dependency_fact", "section_dependency", ["fact_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_section_dependency_fact", table_name="section_dependency")
    op.drop_table("section_dependency")
    op.drop_table("finding_evidence")
    op.drop_table("conflict")
    op.drop_table("claim_citation")
    op.drop_index("ix_fact_predicate_subject", table_name="fact")
    op.drop_index("ix_fact_document", table_name="fact")
    op.drop_table("fact")
    op.drop_index("ix_claim_section_version", table_name="claim")
    op.drop_table("claim")
    op.drop_index("ix_stage_metric_run", table_name="stage_metric")
    op.drop_table("stage_metric")
    op.drop_index("ix_section_version_key", table_name="section_version")
    op.drop_table("section_version")
    op.drop_index("ix_finding_run", table_name="finding")
    op.drop_table("finding")
    op.drop_index("ix_decision_run", table_name="decision")
    op.drop_table("decision")
    op.drop_index("ix_chunk_document", table_name="chunk")
    op.drop_table("chunk")
    op.drop_table("section")
    op.drop_index("ix_run_corpus", table_name="run")
    op.drop_table("run")
    op.drop_index("ix_document_corpus", table_name="document")
    op.drop_table("document")
    op.drop_table("rule")
    op.drop_index("ix_model_cache_stage", table_name="model_cache")
    op.drop_table("model_cache")
    op.drop_table("corpus")
    # ### end Alembic commands ###
