"""fact qualifier for rate-card rows

Revision ID: 78792bb0dacc
Revises: b3f1c07ad2e4
Create Date: 2026-08-17 02:00:36.656929
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '78792bb0dacc'
down_revision: str | None = 'b3f1c07ad2e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact', sa.Column('qualifier', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact', 'qualifier')
    # ### end Alembic commands ###
