"""add document vendor

Revision ID: 97147497b892
Revises: 2ad818202900
Create Date: 2026-08-15 22:28:25.588243
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '97147497b892'
down_revision: str | None = '2ad818202900'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('vendor', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'vendor')
    # ### end Alembic commands ###
