"""add document date

Revision ID: ce09d97cc5d2
Revises: 97147497b892
Create Date: 2026-08-15 22:45:32.142022
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ce09d97cc5d2'
down_revision: str | None = '97147497b892'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('document_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'document_date')
    # ### end Alembic commands ###
