"""Content hashing.

Every "nothing else changed" claim in this system bottoms out here, so the rules are
strict: hashes are computed over normalized content, and the normalization is boring
and total. A hash that changes because trailing whitespace changed would make the
central proof of movement 3 useless — it would report churn on every run and nobody
would trust it by the third demo.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any


def normalize(content: str) -> str:
    """Canonical form for hashing.

    Line endings and trailing whitespace are stripped because they are artifacts of
    the writer, not the content. Nothing else is touched — normalizing case or
    collapsing internal whitespace would hide real edits, which is the opposite of
    what this is for.
    """
    lines = content.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    return "\n".join(line.rstrip() for line in lines).strip()


def content_hash(content: str) -> str:
    """Stable SHA-256 of normalized content. This is the unit of proof for I2."""
    return hashlib.sha256(normalize(content).encode("utf-8")).hexdigest()


def bytes_hash(data: bytes) -> str:
    """Hash of a source file's raw bytes — identity for ingestion dedupe."""
    return hashlib.sha256(data).hexdigest()


def cache_key(
    *,
    stage: str,
    input_text: str,
    model: str,
    prompt_version: str,
) -> str:
    """Key for the content-addressed model cache.

    `prompt_version` is part of the key on purpose. Without it, editing a prompt keeps
    serving answers generated by the previous one — a stale-cache bug that looks like
    the model ignoring your changes, and one you can lose a whole evening to.
    """
    payload = json.dumps(
        {
            "stage": stage,
            "input": normalize(input_text),
            "model": model,
            "prompt_version": prompt_version,
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def stable_json(value: Any) -> str:
    """Deterministic JSON, so composed section content hashes identically across runs
    regardless of dict ordering."""
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
